### ISSUE TITLE
Undefined variable $value_pair in /includes/classes/usu.php on line 341.

### ISSUE THREAD

**Issue by OldNGreyBMR** [lat9/usu#59]
ZC 158a PHP 8.3.4 
I'm not getting the error in zc 2.1.0 but the code is the same.
Should this be valuepair ?

[22-Nov-2024 06:51:44 Australia/Brisbane] Request URI: /zc158a_dev_php8-2/public/search?search_in_description=1&keyword=b%26b%20carb&sort=20a, IP address: 192.168.1.63, Language id 1
#0 E:\Web\zc158a_dev_php8-2\public\includes\classes\usu.php(341): zen_debug_error_handler()
#1 E:\Web\zc158a_dev_php8-2\public\includes\classes\usu.php(223): usu->parse_parameters()
#2 E:\Web\zc158a_dev_php8-2\public\includes\classes\observers\UsuObserver.php(59): usu->href_link()
#3 E:\Web\zc158a_dev_php8-2\public\includes\classes\traits\NotifierManager.php(87): UsuObserver->update()
#4 E:\Web\zc158a_dev_php8-2\public\includes\functions\html_output.php(18): base->notify()
#5 E:\Web\zc158a_dev_php8-2\public\includes\functions\functions_urls.php(121): zen_href_link()
#6 E:\Web\zc158a_dev_php8-2\public\includes\functions\zca_bootstrap_functions.php(140): zen_back_link()
#7 E:\Web\zc158a_dev_php8-2\public\includes\templates\bmh_bootstrap\templates\tpl_search_default.php(96): zca_back_link()
#8 E:\Web\zc158a_dev_php8-2\public\includes\templates\bmh_bootstrap\common\tpl_main_page.php(216): require('E:\\Web\\zc158a_d...')
#9 E:\Web\zc158a_dev_php8-2\public\index.php(94): require('E:\\Web\\zc158a_d...')
--> PHP Warning: Undefined variable $value_pair in E:\Web\zc158a_dev_php8-2\public\includes\classes\usu.php on line 341.

**Comment by lat9** [comment]
Yes, it should!
